### ISSUE TITLE
Let's support more platforms

### ISSUE THREAD

**Issue by simnalamburt** [kinoru/chips#30]
Chips is awesome! I want to spread this program to various platforms.

For POSIX platforms

```bash
#!/bin/bash
# Requirements: libgmp git stack strip upx zip
export TARGET="x86_64-linux" && \
  git clone https://github.com/xtendo-org/chips.git --depth=1 --branch=1.1.2 && \
  cd chips && \
  stack setup && \
  stack build && \
  cp .stack-work/install/"$TARGET"/nightly-2016-10-29/8.0.1/bin/chips chips-"$TARGET" && \
  strip --strip-all --remove-section=.comment --remove-section=.note chips-"$TARGET" && \
  upx -9 --lzma chips-"$TARGET" && \
  zip chips-"$TARGET".zip chips-"$TARGET" && \
  rm chips-"$TARGET"
```

For macOS

```bash
#!/bin/bash
# Requirements: libgmp git stack strip upx zip
export TARGET="x86_64-osx" && \
  git clone https://github.com/xtendo-org/chips.git --depth=1 --branch=1.1.2 && \
  cd chips && \
  stack setup && \
  stack build && \
  cp .stack-work/install/"$TARGET"/nightly-2016-10-29/8.0.1/bin/chips chips-"$TARGET" && \
  strip -u -r chips-"$TARGET" && \
  upx -9 --lzma chips-"$TARGET" && \
  zip chips-"$TARGET".zip chips-"$TARGET" && \
  rm chips-"$TARGET"
```

### TODOs
- [x] x86_64-linux &rarr; https://github.com/xtendo-org/chips/releases/tag/1.1.2
- [x] i386-linux &rarr; [chips-i386-linux.zip](https://github.com/xtendo-org/chips/files/721080/chips-i386-linux.zip)
- [x] x86_64-osx &rarr; https://github.com/xtendo-org/chips/releases/tag/1.1.2 (Sierra support only)
- [ ] aarch64-linux *(I don't have a machine with this ISA)*
- [ ] armv7-linux *(I don't have a machine with this ISA)*
- [ ] x86_64-windows
- [ ] i386-windows

**Comment by xtendo-org** [comment]
Supporting Windows would require major code rewrite, as chips uses `RawFilePath` which is POSIX-only.
